spring.profiles.active: dev

audit.amount:
  deposit: 99
  withdrawal: 99

---

spring:
  profiles: dev
debug: false

---

spring:
  profiles: prod
debug: false

---
hibernate:
  dialect: org.hibernate.dialect.H2Dialect

spring:
  datasource:
    url: jdbc:h2:mem:./bank
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: create-drop

